name: "Validate OpenAPI specification"
on:
  push:
    branches:
      - main
    tags:
      - v*
    paths-ignore:
      - "**.md"

  pull_request:
    types: [ opened, synchronize ]
    paths-ignore:
      - "**.md"

  workflow_dispatch:


jobs:
  validate-oicp-v230-specification:
    name: "Validate the OICP 2.3.0 OpenAPI specification"
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Swagger Editor Validator
        id: validate
        uses: swaggerexpert/swagger-editor-validate@v1
        with:
          definition-file: ./2.3.0/api/2.3.0.spec.yml

      - name: Setup Go
        if: steps.validate.outcome == 'success'
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.0

      - name: Install Oapi Codegen
        if: steps.validate.outcome == 'success'
        working-directory: ./2.3.0
        run: |
          go install github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@latest
          go generate ./...

      - name: Push the generated code
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "[Autogen] Generated client and server code from OpenAPI spec"